name: Deploy LMS DEV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/lms-dev/lms-project

            git remote prune origin
            git fetch --prune --all
            git reset --hard origin/main

            cd client
            npm install
            npm run build
            chmod -R 755 /var/www/lms-dev/lms-project/client/dist
            chown -R www-data:www-data /var/www/lms-dev/lms-project/client/dist

            cd ../server
            npm install

            pm2 restart lms-dev --update-env || pm2 start server.js --name "lms-dev"
            systemctl reload nginx
